# Generated by Django 2.1.15 on 2020-10-31 12:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20201030_1529'),
    ]

    operations = [
        migrations.AlterIndexTogether(
            name='rating',
            index_together=set(),
        ),
    ]
